name: enough_media
description: Extensible collection of media viewers for preview and interactive experiences.
version: 0.2.0+1
homepage: https://github.com/enough-software/enough_media

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: any
  photo_view: ^0.10.3
  flutter_sound_lite: ^7.6.1+1
  video_player: ^1.0.1
  chewie: ^0.12.2
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: